name: Update Metadata

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-meta:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0   

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Metadata JSON
        run: node scripts/gen-meta.js

      - name: Inject GITHUB_SHA into HTML
        run: |
          # Ubah path ke file HTML yang sesuai (misal index.html atau docs/index.html)
          sed -i "s|<!--GITHUB_SHA-->|<script>window.GITHUB_SHA='${{ github.sha }}';</script>|" index.html

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plugin/meta/*.json index.html
          git diff --cached --quiet || git commit -m "🔄 Update metadata JSON and inject SHA"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD
