name: Update Metadata

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-meta:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0   # penting supaya git log lengkap

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Metadata JSON
        run: node scripts/generate-meta.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plugin/meta/*.json
          git diff --cached --quiet || git commit -m "🔄 Update metadata JSON files"
          
      - name: Push changes
        run: git push origin HEAD
