name: Generate Metadata JSON

on:
  push:
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  generate-meta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (if needed)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Run metadata generation script
        run: node .github/scripts/gen-meta.js

      - name: Commit and push metadata
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plugin/meta/*.json
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "🔄 Auto-update metadata from markdown files"
            git push
          fi
